### ISSUE TITLE
Marginal variance using `var`

### ISSUE THREAD

**Issue by jkbest2** [ElOceanografo/GaussianMarkovRandomFields.jl#1]
I'm not sure that this line is correct:

https://github.com/ElOceanografo/GaussianMarkovRandomFields.jl/blob/aaa1ea35e1acb2bb0b2f57d1dde2f44c7bcac5a4/src/GaussianMarkovRandomFields.jl#L64

Couterexample:

```julia
Σ = [1.0 0.5; 0.5 1.0]
Q = inv(Σ)
1 ./ diag(Q)
```

gives

```julia
2-element Array{Float64,1}:
 0.75
 0.75
```

[This report](https://cds.cern.ch/record/848064/files/cer-002531398.pdf) by Håvard Rue provides a method for calculating the marginal variances directly. I'll see if I can implement it in the next few days.

**Comment by ElOceanografo** [comment]
Closed by https://github.com/ElOceanografo/GaussianMarkovRandomFields.jl/pull/2
